fix build, improve service file and fstat plugins, fix restart command...
initng/initng pull request #18
Opened 2017-04-24 12:40 UTC by gcannent

**fix build for cross compilation, add build option to add or remove some of the additional modules:**
_patching file Jamrules
patching file config.h.acr
patching file config.jam.acr
patching file configure.acr
patching file include/Jamfile
patching file include/initng/Jamfile
patching file src/main/active_db/count.c
patching file src/main/depend/any_depends_on.c
patching file src/main/depend/stop_dep_met.c
patching file src/main/handler/stop_all.c
patching file src/main/interrupt/handle.c
patching file src/main/main/ready_to_quit.c
patching file src/modules/Jamfile
patching file src/modules/also/initng_also.c
patching file src/modules/chroot/initng_chroot.c
patching file src/modules/conflict/initng_conflict.c
patching file src/modules/cpout/initng_cpout.c
patching file src/modules/fmon/initng_fmon.c
patching file src/modules/lockfile/initng_lockfile.c
patching file src/modules/netdev/initng_netdev.c
patching file src/modules/ngc4/Jamfile
patching file src/modules/nge/Jamfile
patching file src/modules/suid/initng_suid.c
patching file src/modules/syslog/initng_syslog.c
patching file src/tools/Jamfile_

**fix service file loading:**
_patching file src/modules/service_file/bp.c
patching file src/modules/service_file/runiscript.c_

**fix ipc reload:**
_patching file src/modules/ngc4/libngcclient.c_

**fix syslog signal handler:**
_patching file src/modules/syslog/initng_syslog.c_

**reboot faster:**
_patching file src/main/depend/stop_deps.c_

**fix restart command:**
_patching file src/main/active_db/find.c
patching file src/modules/ngc4/initng_ngc4.c
patching file src/modules/stcmd/initng_stcmd.c_

**improve and fix preinit to optionally use a script (to mount the filesystem):**
_patching file src/preinit/main.c_

**fix wait on restart:**
_patching file src/modules/ngc4/ngc4.c_

**fix fstat plugin (it is still polling for the moment):**
_patching file contrib/initng-usplash/initng-usplash-shutdown.c
patching file contrib/initng-usplash/initng-usplash.c
patching file src/main/depend/start_dep_met.c
patching file src/main/depend/stop_dep_met.c
patching file src/modules/daemon/initng_daemon.c
patching file src/modules/fstat/initng_fstat.c
patching file src/modules/ngc4/libngcclient.c
patching file src/modules/service/initng_service.c
patching file src/modules/service_file/initng_service_file.c_

2017-06-13 00:09 UTC, ismaell commented
Inotify is linux-specific, InitNG can't use that directly, but an abstraction that uses inotify/kqueue and falls back to polling would be OK.

2017-08-25 20:38 UTC, ismaell requested changes
Commit 1b76f7ddceab9388a029c1cde5623b756a656a6 is way too large, it should be split.

There's many unjustified changes.

2017-08-25 20:38 UTC, ismaell commented on contrib/initng-usplash/initng-usplash-shutdown.c
> +		/* reset error every time, or you get an cannot connect to socket */
It's either "can not" or "can't".

2017-08-25 20:38 UTC, ismaell commented on contrib/initng-usplash/initng-usplash.c
> +		/* reset error every time, or you get an cannot connect to socket */
Ditto.

2017-08-25 20:38 UTC, ismaell commented on src/main/depend/start_dep_met.c
> +				F_("Service %s cannot be started because a "
Ditto.

2017-08-25 20:38 UTC, ismaell commented on src/main/depend/stop_dep_met.c
> +				F_("Service %s cannot be started because a "
Ditto.

2017-08-25 20:38 UTC, ismaell commented on config.h.acr
> +#define VARDIR              "/run/initng"
Why do you want to replace `@LOCALSTATEDIR@` here?

2017-08-25 20:38 UTC, ismaell commented on src/main/depend/stop_deps.c
> +		if (initng_depend(current, service) == TRUE)
What's the rationale behind this change?

2017-08-25 20:38 UTC, ismaell commented on src/modules/chroot/initng_chroot.c
> +#define _DEFAULT_SOURCE
Both should be defined, just in case the system is using an old glibc.

2017-08-25 20:38 UTC, ismaell commented on src/modules/daemon/initng_daemon.c
> +	.alarm = &handle_DAEMON_WAITING_FOR_START_DEP
Why?

2017-08-25 20:38 UTC, ismaell commented on src/modules/daemon/initng_daemon.c
> +	.alarm = &init_DAEMON_START_DEPS_MET
Why?

2017-08-25 20:38 UTC, ismaell commented on src/modules/fmon/initng_fmon.c
> +#define _DEFAULT_SOURCE
Both should be defined.

2017-08-25 20:38 UTC, ismaell commented on src/modules/fstat/initng_fstat.c
> +	.description = "If this file do not exist, this service will FAIL "
Should say "does not".

2017-08-25 20:38 UTC, ismaell commented on src/modules/fstat/initng_fstat.c
> +	.description = "If this file do not exist after, the service will be "
Ditto.

2017-08-25 20:38 UTC, ismaell commented on src/modules/fstat/initng_fstat.c
> +			initng_handler_set_alarm(service, 1);
So the idea to adding alarms is to implement a timeout?

2017-08-25 20:38 UTC, ismaell commented on src/modules/ngc4/Jamfile
> +#InstallLink libngcclient.so : $(DESTDIR)$(libdir) : libngcclient.so.0 ;
Why?

2017-08-25 20:38 UTC, ismaell commented on src/modules/ngc4/libngcclient.c
> +	}
Why not make this loop look like this:

	for (int retries = 1; !(sock = ...) && retries > 0; retries--) {
		kill(1, SIGHUP);
		usleep(50000);		
	}

2017-08-25 20:38 UTC, ismaell commented on src/modules/ngc4/libngcclient.c
> +					      "cannot return if this "
"can't" or "can not"

2017-08-25 20:40 UTC, ismaell requested changes

2017-08-25 20:40 UTC, ismaell commented on src/modules/ngc4/ngc4.c
> +char servicename[2048] = {0};
This can't happen. State can't live on the heap except for `g` (which at some point will be removed).

2017-08-25 20:43 UTC, ismaell commented
Please split the changes into smaller commits and group them by topic in independent PRs

2017-08-28 09:43 UTC, gcannent commented on contrib/initng-usplash/initng-usplash-shutdown.c
> +		/* reset error every time, or you get an cannot connect to socket */
I will switch to *can't* but grammatically speaking the negative form for *can* is either *cannot* or *can't*.

2017-08-28 09:43 UTC, gcannent commented on contrib/initng-usplash/initng-usplash.c
> +		/* reset error every time, or you get an cannot connect to socket */
same here

2017-08-28 09:43 UTC, gcannent commented on src/main/depend/start_dep_met.c
> +				F_("Service %s cannot be started because a "
same here

2017-08-28 09:43 UTC, gcannent commented on src/main/depend/stop_dep_met.c
> +				F_("Service %s cannot be started because a "
same here

2017-08-28 09:44 UTC, gcannent commented on config.h.acr
> +#define VARDIR              "/run/initng"
error. I will revert this part

2017-08-28 09:46 UTC, gcannent commented on src/main/depend/stop_deps.c
> +		if (initng_depend(current, service) == TRUE)
Stop takes to much time with depend_deep. I can revert this part and keep the change only for us.

2017-08-28 09:46 UTC, gcannent commented on src/modules/chroot/initng_chroot.c
> +#define _DEFAULT_SOURCE
You are right I will add both.

2017-08-28 09:47 UTC, gcannent commented on src/modules/fmon/initng_fmon.c
> +#define _DEFAULT_SOURCE
same here

2017-08-28 09:47 UTC, gcannent commented on src/modules/fstat/initng_fstat.c
> +	.description = "If this file do not exist, this service will FAIL "
exactly.

2017-08-28 09:47 UTC, gcannent commented on src/modules/fstat/initng_fstat.c
> +	.description = "If this file do not exist after, the service will be "
same here

2017-08-28 09:48 UTC, gcannent commented on src/modules/ngc4/Jamfile
> +#InstallLink libngcclient.so : $(DESTDIR)$(libdir) : libngcclient.so.0 ;
To solve a link issue with our arm compile in the yocto environment. I can keep this change only for us.

2017-08-28 09:49 UTC, gcannent commented on src/modules/ngc4/libngcclient.c
> +					      "cannot return if this "
same as above.

2017-08-28 09:51 UTC, gcannent commented
Thanks for taking the time to review this bunch of changes. 
This is my first time at this process. I will recreate smaller change requests to make it clearer. I think we can discard this one.

2017-08-28 12:03 UTC, ismaell commented on contrib/initng-usplash/initng-usplash-shutdown.c
> +		/* reset error every time, or you get an cannot connect to socket */
"Can not" is equally valid; currently, "can't" appears more frequently, followed by "can not" and then "cannot", so it would be easier to normalize to "can't". That said, it should be a different PR, and it adds no actual value.

2017-08-28 12:05 UTC, ismaell commented on src/main/depend/stop_deps.c
> +		if (initng_depend(current, service) == TRUE)
Not using a deep search means the dependency may actually exist. One solution to speedup the search would be to build a flattened index.

2017-08-28 12:06 UTC, ismaell commented on src/modules/ngc4/Jamfile
> +#InstallLink libngcclient.so : $(DESTDIR)$(libdir) : libngcclient.so.0 ;
Please.

2017-09-12 21:53 UTC, ismaell commented on src/main/env/new.c
> +		env[nr] = initng_toolbox_strdup(initng_environ[nr]);
why strdup here?

2017-09-13 07:53 UTC, gcannent commented on src/main/env/new.c
> +		env[nr] = initng_toolbox_strdup(initng_environ[nr]);
This is for consistency, all the other arguments for the env are allocatated on the heap, which, I am sure, survives the execve done sometimes after.

2017-09-13 07:55 UTC, gcannent commented on src/main/env/new.c
> +		env[nr] = initng_toolbox_strdup(initng_environ[nr]);
I am still planning,  to resubmit my changes into smaller separate pull requests.

2021-09-01 08:09 UTC, closed without merging